//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiltSFX.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuiltSFX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap BeastTamer {
            get {
                object obj = ResourceManager.GetObject("BeastTamer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 壓縮等級愈高代表壓縮效果較佳且花費較多時間 的當地語系化字串。
        /// </summary>
        internal static string CompressionLevelToolTip {
            get {
                return ResourceManager.GetString("CompressionLevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Execute {
            get {
                object obj = ResourceManager.GetObject("Execute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 計算檔案大小 (封裝時受應用程式檔案大小限制) 的當地語系化字串。
        /// </summary>
        internal static string FileSizeToolTip {
            get {
                return ResourceManager.GetString("FileSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Quilt SFX 製作工具
        ///
        ///如何使用 :
        ///1 加入檔案或資料夾
        ///2 設定打包參數
        ///3 修改 Stub 程式組使用者設定值
        ///3 加入 Stub 程式組
        ///4 進行打包
        ///
        ///輸出產物為標準應用程式檔案
        ///可作為安裝程式發布或檔案保存使用
        ///
        ///附註說明 :
        ///貓貓最可愛了 ~ 喵嗚 ฅ^•ω•^ฅ ~ 的當地語系化字串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (可選) 決定產出自解檔程式圖標 的當地語系化字串。
        /// </summary>
        internal static string IconToolTip {
            get {
                return ResourceManager.GetString("IconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Profile {
            get {
                object obj = ResourceManager.GetObject("Profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 總體壓縮處理進度 的當地語系化字串。
        /// </summary>
        internal static string ProgressAllToolTip {
            get {
                return ResourceManager.GetString("ProgressAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前檔案壓縮處理進度 的當地語系化字串。
        /// </summary>
        internal static string ProgressNowToolTip {
            get {
                return ResourceManager.GetString("ProgressNowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定封裝外殼 (支援檔案 : C# 程式碼、Any CPU .Net DLL、二進位資源檔案) 的當地語系化字串。
        /// </summary>
        internal static string StubToolTip {
            get {
                return ResourceManager.GetString("StubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定封裝檔案是否需要系統管理員權限執行 的當地語系化字串。
        /// </summary>
        internal static string UACToolTip {
            get {
                return ResourceManager.GetString("UACToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 using System.Reflection;
        ///using System.Resources;
        ///using System.Runtime.InteropServices;
        ///
        ///[assembly: AssemblyTitle(&quot;{Title}&quot;)]
        ///[assembly: AssemblyDescription(&quot;{Description}&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;{Company}&quot;)]
        ///[assembly: AssemblyProduct(&quot;{Product}&quot;)]
        ///[assembly: AssemblyCopyright(&quot;{Copyright}&quot;)]
        ///[assembly: AssemblyTrademark(&quot;{Trademark}&quot;)]
        ///[assembly: AssemblyCulture(&quot;&quot;)]
        ///
        ///[assembly: ComVisible(false)]
        ///
        ///[assembly: Guid(&quot;{Guid}&quot;)]
        ///
        ///[assembly: Assembly [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
